# Generic project template
# Usage: tmuxinator start project <project-name>
#
# Creates a session with:
#   - nvim (left pane, 50%)
#   - happy (top-right pane, 25%)
#   - R or Julia REPL (bottom-right pane, 25%, auto-detected)

name: <%= @args[0] %>
root: <%= @args[1] || "~/code/#{@args[0]}" %>

startup_window: main

on_project_start: |
  # Set pane titles after layout is created
  tmux select-pane -t 0 -T "nvim"
  tmux select-pane -t 1 -T "happy:main"
  tmux select-pane -t 2 -T "repl"

windows:
  - main:
      layout: main-vertical
      panes:
        - nvim .
        - happy
        - >-
          if [ -f Project.toml ]; then
            julia --project=.
          elif [ -f DESCRIPTION ]; then
            R
          else
            echo "No R or Julia project detected"
            zsh
          fi
