[metadata]
name = "r-history"
description = "Radian/R REPL command history"
requirements = []

[source]
command = "grep '^+' ~/.radian_history | sed 's/^+//' | sed '1!G;h;$!d'"
display = "{0}"
output = "{0}"
no_sort = true
frecency = false
