
install.packages("devtools")
install.packages("remotes")
install.packages("tidyverse")
install.packages("renv")
install.packages("data.table")
install.packages("here")
install.packages("targets")
install.packages("languageserver")
install.packages("lintr")
install.packages("styler")
install.packages("httpgd")
install.packages("spelling")
install.packages("testthat")
install.packages("tinytest")
install.packages("git2r")
install.packages("rmarkdown")
install.packages("vdiffr")
remotes::install_github("mdlincoln/docthis")
remotes::install_github("lorenzwalthert/precommit")
remotes::install_github("milesmcbain/fnmate")
install.packages("tinytex")
remotes::install_github("stan-dev/cmdstanr")
remotes::install_github("stan-dev/loo")
install.packages("rstan")
install.packages("roxygen2")

tinytex::install_tinytex()

cmdstanr::install_cmdstan()
